[toolchain]
channel = "1.80.0"
components = [ "rustfmt", "rustc-dev" ]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-msvc",
  "aarch64-unknown-linux-musl",
  "armv7-unknown-linux-musl"
]
profile = "default"
